### ISSUE TITLE
Tracking: Lists Feature MVP 

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#1662]
## List creation flow MVP
- [x] https://github.com/open-sauced/app/issues/1672
- [ ] https://github.com/open-sauced/app/issues/1671
- [x] https://github.com/open-sauced/app/issues/1670
- [x] https://github.com/open-sauced/app/issues/1669
- [x] https://github.com/open-sauced/app/issues/1668
- [ ] https://github.com/open-sauced/app/issues/1671

## List Page MVP (only overview, activity and contributors table tabs) 
- [ ] https://github.com/open-sauced/app/pull/1569
- [ ] https://github.com/open-sauced/app/pull/1594
- [x] https://github.com/open-sauced/app/issues/1708

**Comment by bdougie** [comment]
@isabensusan I updated the OP (original post) to include all the open issues. Creating a video to update the community in the discord and thought it might be easier to see what is still in progress and what is merged.
