### ISSUE TITLE
Working draft of frontend API requirements for Lists chart features

### ISSUE THREAD

**Issue by foxyblocks** [open-sauced/app#1701]
# List Stats API chages proposal

This is a proposal for how to structure the API changes needed to complete the frontend changes for the Lists feature currently in progress.

# List CRUD

- [ ]     **TODO, write these out**

# List Stats

## Most active contributors card

[![](https://user-images.githubusercontent.com/555044/262432101-dbfc1190-101b-4f6b-b50e-263ecc66d86f.png)](https://user-images.githubusercontent.com/555044/262432101-dbfc1190-101b-4f6b-b50e-263ecc66d86f.png)

`GET /lists/{listId}/stats/most-active-contributors`

Paginated endpoint of contributors for a particular list with their aggregated contributions broken out by type

  

### Params

```typescript
interface Params {
  timeFrame: "7d" | "30d"; // default "7d"
  contributorType: "all" | "active" | "new" | "alumni"; // default 'all'
  sortBy: "most_active" | "???";
}
```

#### todo

- [ ]     Confirm valid timeframe options
- [ ]     Confirm valid contributor options

### Result

```json
{
  "data": [
    {
      "username": 'foxyblocks',
      "contributions": {
        "commits": 42,
        "prsCreated": 42,
        "prsReviewd": 42,
        "issuesCreated": 42,
        "comments": 42,
      }
    },
    //...
 ]
  "meta": {
    "page": 1,
    "limit": 50,
    "itemCount": 71,
    "pageCount": 2,
    "hasPreviousPage": false,
    "hasNextPage": true
   }
}
```

#   

## Contributions Evolution

[![](https://user-images.githubusercontent.com/555044/262432189-cfdc4bae-527f-4830-a9ba-bce6a77a742f.png)](https://user-images.githubusercontent.com/555044/262432189-cfdc4bae-527f-4830-a9ba-bce6a77a742f.png)

`GET /lists/{listId}/stats/contributions-evolution-by-type`

Get's an array of timeframes with the aggregate number of contributions for each contribution type scoped to a particular list. The time granularity of the data set should be increased or decreased based on the size of the overall time series. For example if we are looking at the past 7 days then each item of the array should represent a 1 day window

### Params

```typescript
interface Params {
  timeFrame: "7d" | "30d"; // default "7d"
  contributorType: "all" | "active" | "new" | "alumni"; // default 'all'
}
```

### Result

```json
{
  "data": [
    {
      "timeStart": "DateTime",
      "timeEnd": "DateTime",
      "contributions": {
         "commits": 42,
        "prsCreated": 42,
        "prsReviewd": 42,
        "issuesCreated": 42,
        "comments": 42,
      }
    },
    //...
  ]
}
```

## Contributions by project

<img width="787" alt="CleanShot 2023-08-22 at 11 16 31@2x" src="https://github.com/open-sauced/app/assets/555044/68fb3d9e-b378-4e65-ae25-6f8b06c0d038">

`GET /lists/[listId]/stats/contributions-by-project`

List of projects that contributors in the list have contributed to and the aggregate number of total contributions made to that project.

```json
{
  "data": [
    {
      "orgId": "open-sauced",
      "projectId": "/hot",
      "contributions": 200,
    }, 
  //...
]
```

  
<img width="784" alt="CleanShot 2023-08-22 at 11 23 49@2x" src="https://github.com/open-sauced/app/assets/555044/5e0a4294-5963-42c0-951c-382af3236f0d">

  

`GET /lists/[listId]/stats/top-project-contributions-by-contributor?projectId=[projectId]`

List of contributors (belonging to a particular list and scoped to a particular project) and their aggregate contributions to said project, broken out by contribution type. This list would be limited to the top 20 contributors.

  

```typescript
interface Params {
  projectId: string
}
```

  

```json
{
  "data": [
    {
      "username": "foxyblocks",
      "contributions": {
        "commits": 42,
        "prsCreated": 42,
        "prsReviewd": 42,
        "issuesCreated": 42,
        "comments": 42,
      }
    },
    //...
 ]
```
## Contributions Evolution by Contributor Type

![](https://t20553800.p.clickup-attachments.com/t20553800/29157b6b-a588-4d14-8a8f-0c17e23bf5b3/CleanShot%202023-08-22%20at%2010.36.12%402x.png)

  

`GET /lists/{listId}/stats/contributions-evolution-by-contributor-type`

Get's an array of timeframes with the aggregate number of contributions for each contributor type scoped to a particular list. The time granularity of the data set should be increased or decreased based on the size of the overall time series. For example if we are looking at the past 7 days then each item of the array should represent a 2 hour window of that 7 days. This would give us 84 data points. These number can obviously be adjusted as we see fit but we'll probably want roughly the same number of data points per timeFrame option.

### Params

```typescript
interface Params {
  timeFrame: "7d" | "30d"; // default "7d"
  contributorType: "all" | "active" | "new" | "alumni"; // default 'all'
}
```

### Result

```json
{
  "data": [
    {
      "timeStart": "DateTime",
      "timeEnd": "DateTime",
      "contributions": {
         "active": 4222,
         "new": 1233,
         "alumni": 4242,
      }
    },
    //...
  ]
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by jpmcb** [comment]
Re-opening to tackle the
```
GET /lists/[listId]/stats/top-project-contributions-by-contributor?projectId=[projectId]
```
endpoint

**Comment by jpmcb** [comment]
Oh looks like I did land that one:

https://beta.api.opensauced.pizza/#/User%20Lists%20service/getContributorContributionsByProject

Example usage:

```
curl -X 'GET' \
  'http://localhost:3003/v1/lists/17e0f1c2-c556-4734-bfc4-86d43efc4087/stats/top-project-contributions-by-contributor?repoId=499330806' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer <redacted>'
```

```json
[
  {
    "login": "brandonroberts",
    "commits": 120,
    "prs_created": 123
  },
  {
    "login": "jpmcb",
    "commits": 51,
    "prs_created": 21
  }
]
```

This is a list with both me and brandon. And `499330806` is the id for our API repo. Does that work for you @foxyblocks ?

**Comment by foxyblocks** [comment]
@jpmcb Yeah, but is there a technical reason we don't have all 5 stats for these endpoints?
- commits
- prs_created
- issues_created
- prs_reviewed
- comments

**Comment by jpmcb** [comment]
Unfortunately yes: we aren't _currently_ indexing issues, pr reviews, or comments:
- https://github.com/open-sauced/api/issues/321
- https://github.com/open-sauced/api/issues/322
- https://github.com/open-sauced/api/issues/323
I was hoping to dive into those 3 issues soon but unsure where that will put us delivering the list feature as a whole

**Comment by brandonroberts** [comment]
Initial charts have been developed
