### ISSUE TITLE
[Front-End] Implement User Avatar

### ISSUE THREAD

**Issue by chadstewart** [open-sauced/app#19]
Ideally, we want to be able to:
- [x] Set the size of the avatar #30 
- [x] Be able to define the `alt` attribute #30 
- [x] Set the image URL dynamically #30 
- [ ] #31
