### ISSUE TITLE
Feature: Update creation flow on Insight pages

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#2854]
### Type of feature

🍕 Feature

### Current behavior

We currently have 3 different creation flows that aren't consistent

**Workspace creation flow:**
<img width="500" alt="image" src="https://github.com/open-sauced/app/assets/27322879/3c8823fe-8ba1-487f-be12-e164148bfb03">

**Repository Insight creation flow**
<img width="500" alt="image" src="https://github.com/open-sauced/app/assets/27322879/e54af560-313b-4c7b-8fb4-c94b2a85ece9">

**Contributor Insight creation flow**
<img width="500" alt="image" src="https://github.com/open-sauced/app/assets/27322879/b0b45c0b-7880-4d97-b295-4dc4cde32fa8">

### Suggested solution

We want to update the Contributor and Insight creation flows to make them consistent with the Workspace creation flow and improve overall usability.

## Tasks
- [ ] Normalize copy / language
- [ ] Normalize typography
- [ ] Update the "add repository" flow using the new workspaces modal 
- [ ] Update the "add contributors" flow using the new workspaces modal 

cc @zeucapua 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs
