### ISSUE TITLE
QA tracking issue - ui bugs

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#295]
@chhristopher went through the app and identified UI inconsistencies. Creating this track all that work. https://app.clickup.com/20553800/v/l/f/132100400

- [x] https://github.com/open-sauced/insights/issues/287
- [x] https://github.com/open-sauced/insights/issues/288
- [x] https://github.com/open-sauced/insights/issues/289
- [x] https://github.com/open-sauced/insights/issues/289
- [x] https://github.com/open-sauced/insights/issues/290
- [x] https://github.com/open-sauced/insights/issues/291
- [x] https://github.com/open-sauced/insights/issues/292
