### ISSUE TITLE
Tracking: "Repo URL" proof of concept

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#2961]
## Problem
In our platform today, we have no easy way to search for a specific repo and get quick insights. We have the information in the API, but we are just not surfacing it anywhere.

### Context
One of our upcoming product milestones is [Repo Pages](https://docs.google.com/document/d/1edaUdQ4KtVP69AGox6-fFWn5iIXO7uCMS1etnwpLL78/edit?usp=sharing), where we want to build individual pages for repositories the same way we have pages for user profiles.

## Suggested Solution
As a first step to getting there, we want to do a quick prototype for repo urls where the user can type `app.opensauced.pizza/<org name>/<repo name>` and see a simple page containing:
- the repository's icon, name and description as the header
- a bar chart with the repository's stars over time
- a bar chart with the repository's forks over time

For the URL path we want to follow GitHub's convention of: `https://github.com/microsoft/vscode` where you can find any repository by just adding "/organization/repository" to the URL to get to the repository page.

The necessary API endpoints are:
- [Repository service](https://api.opensauced.pizza/#/Repository%20service/findAllReposWithFilters)
- [Histogram generation service](https://api.opensauced.pizza/#/Histogram%20generation%20service)

## Task breakdown
- [x] Create URL path structure
- [x] Show repository title, icon and description on page
- [x] Create prototype chart for stars
- [ ] Create prototype chart for forks

## Related Issues
#2985

**Comment by bdougie** [comment]
We currently are not tracking the following things. I figured I'd leave a comment in case there is context I am missing.

- Mobile view is not working. I'd love to start a best practice for mobile first in the future. The feature is not shareable behind a feature flag and I exclusively find myself in a position where I QA most features from the phone.
- The 10% from last period is static and I want to ask about it, but not sure if it is planned work or not. 

I really think with the above addressed, aside from some UI polish, we could start sharing this feature for feedback.

**Comment by bdougie** [comment]
> * king. I'd love to start a best practice for

These things have been addressed in the follow PRS - https://github.com/open-sauced/app/pull/3081 https://github.com/open-sauced/app/pull/3094. The second is removing items. 

## Searching repo pages. 

I'd love to scope in as a low priority issue to add repo pages to the command pallet. I am already planing content around this new interaction and being able to quickly recall a repo to show would be 👨🏾‍🍳 💋
 
![Screen Shot 2024-04-03 at 5 03 29 PM](https://github.com/open-sauced/app/assets/5713670/e5081f93-721d-4d2e-aa11-6672d31969c6)
