### ISSUE TITLE
Tracking Issue: Devstats

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#3082]
We have a number of issues in the API ready to implement in the UI. I'd love to start tracking the process towards getting these things into the Workspaces product. 

The ones would ideal get implemented in the current sprint. @isabensusan let me know if we are able start prioritizing the planning for this. 

## API issues needed
- [ ] https://github.com/open-sauced/api/issues/625
- [ ] https://github.com/open-sauced/api/issues/668
- [ ] https://github.com/open-sauced/api/issues/623
- [x] https://github.com/open-sauced/api/issues/667
- [x] https://github.com/open-sauced/api/issues/664
- [ ] https://github.com/open-sauced/api/issues/623
- [x] https://github.com/open-sauced/api/issues/667

## Frontend issues

TBD

**Comment by brandonroberts** [comment]
Currently, we're blocked on design as we're revisiting what to display on the workspace dashboard.
