### ISSUE TITLE
Feature: open access to StarSearch to all users

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#3434]
### Suggested solution

We want users to be able to see StarSearch, but if they are not logged in, we want to prompt them to do so to use StarSearch.

### Todo:

- [ ] Remove feature flag code
- [ ] Add "log in" modal
- [ ] Redirect `/waitlist` to `/star-search`

We can achieve this by showing the UI to non-logged users, but whenever the user:
- Clicks on one of the suggested prompts
- Clicks on the input bar
We show a modal prompting them to signup.

For mobile we should use the drawer component

<img width="800" alt="image" src="https://github.com/open-sauced/app/assets/27322879/4cacce09-f917-4cac-9a04-c26b5cf75c90">

<img width="400" alt="image" src="https://github.com/open-sauced/app/assets/27322879/9300a246-712d-4512-9044-3a68bfae98ac">

## Copy
title: Log in to try StarSearch!
content: StarSearch is currently available only to logged in users. Log in or create an account to get access!

Background image
&nb;sp

<img width="250" alt="image" src="https://github.com/open-sauced/app/assets/27322879/6cf089f2-4ef9-4ca7-a3f7-dc4a126d7468">

**Comment by jpmcb** [comment]
I don't believe there's anything on the API to be done since the `v2/star-search/stream` endpoint is open to anyone/everyone. Let me know how I can support / accelerate this work!!
