### ISSUE TITLE
Feature: Tracking Repo Pages (Miscellaneous)

### ISSUE THREAD

**Issue by zeucapua** [open-sauced/app#3738]
**Events to capture**
- [x] Contributor Chart: Filter contributor types
- [x] Contributor Confidence: Learn more link to docs
- [x] Star/Fork Chart: Daily, History buttons
