### ISSUE TITLE
enhancement: Latest polishes before Hacktoberfest

### ISSUE THREAD

**Issue by eryc-cc** [open-sauced/app#374]
## Summary

Tracking tasks to make the app more polished before Hacktoberfest:

### Dashboard
- [ ] Add loading state to components #158
- [x] Update nav, context, and background styles (to match latest design)
- [x] #406
- [x] #407
- [x] #428

### Reports
- [x] Center Reports screen
- [x] Update table styles to match the Repositories Table

### Contributors
- [x] #408
- [ ] Add features: sorting, search, pagination, page title, just like Repositories
