### ISSUE TITLE
Tracking Issue: Complete User Flows

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#390]
## emails
- [x] https://github.com/open-sauced/insights/issues/125
- [x] https://github.com/open-sauced/insights/issues/112

## onboarding
- [x] https://github.com/open-sauced/insights/issues/131
- [x] https://github.com/open-sauced/insights/issues/382
- [x] #396

## sharing
- [x] https://github.com/open-sauced/insights/issues/153
- [x] https://github.com/open-sauced/insights/issues/225

## Need more user functionality
- [x] https://github.com/open-sauced/insights/issues/159
- [x] https://github.com/open-sauced/insights/issues/253
