### ISSUE TITLE
Tracking Issue: Scatter Chart needs to work

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#399]
- [x] https://github.com/open-sauced/insights/issues/372
- [x] https://github.com/open-sauced/insights/issues/373
- [x] https://github.com/open-sauced/insights/issues/465
