### ISSUE TITLE
Tracking Issue: Connect Contributor API Data

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#400]
- [x] https://github.com/open-sauced/gs-api.opensauced.pizza/issues/17
- [x] https://github.com/open-sauced/gs-api.opensauced.pizza/issues/18
- [x] https://github.com/open-sauced/gs-api.opensauced.pizza/issues/19
- [x] https://github.com/open-sauced/gs-api.opensauced.pizza/issues/20
- [x] #404
- [x] #403
- [x] #402
