### ISSUE TITLE
Open Source Checklist

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#488]
- [x] Delete [discussions](https://github.com/open-sauced/insights/discussions)
- [x] Check issues for sensitive info
- [ ] Craft announcement
- [ ] Lock down https://gs-api.opensauced.pizza/
- [ ] use registration? 
- [ ] dev OPS notifications
- [ ] Roll any necessary keys/environment vars
