### ISSUE TITLE
tracking: Insights on individual Repositories

### ISSUE THREAD

**Issue by eryc-cc** [open-sauced/app#550]
## Summary

Essentially, OpenSauced will have a GitHub-like structure for accessing individual repositories, or contributors. **This issue tracks the individual repositories.**

- ClickUp documentation
- Figma Link

---

### Design:
- [ ] design:

### Front-end:
- [x] #558

### Back-end:
- [x] repo routes exist 
- [ ] public user APIs to list our public enabled users are required
- [ ] a way to publish public user profiles is required and some options for it (public, public once logged in, public by default, etc)

---

**Reference:**
> @bdougie I'm going to close this issue and open another one specifically for having insights on individual repos, or contributors via `insights.opensauced.pizza/<ORG/USER>/<REPO>` url.

_Originally posted by @pixelsbyeryc in https://github.com/open-sauced/insights/issues/397#issuecomment-1287205322_
