### ISSUE TITLE
feature: Transfer repository/contributor insights page to a new workspace

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#647]
### Tasks

- [x] API changes for Repository Insights (done: [/api  PR  #613](https://github.com/open-sauced/api/pull/613) )
- [x] API changes for Contributor Insights (todo: [/api issue #619](https://github.com/open-sauced/api/issues/619))
- [ ] Front end changes for Repository Insights
- [ ] Front end changes for Contributor Insights

### Type of feature

Select the type of feature request, the lowercase should also be the PR prefix.

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

### Current behavior

> I have been creating demos, but it would ideal to transfer this to Erin

Currently, users can create repository and contributor insights in a Workspace but can transfer it to a different one. 

Being able to transfer insights would be useful not only in the context of Brian's demos, but I can see this being handyalso for users that experiment or create insight pages on their personal workspaces and want to transfer them to their org workspace.

<img width="790" alt="Screen Shot 2022-12-08 at 9 57 30 AM" src="https://user-images.githubusercontent.com/5713670/206528507-42566085-4bae-4eaf-a705-1bdd826de2c9.png">

other notes
- standing in python or ML
- contribution types
- new issues
- topics - sort which is active and will take contributions

### Suggested solution

We need a user flow where a user:

1. User creates a contributor or repository insight page
2. User goes to insight settings and sees the option to "Move to a different Workspace" (should probably be in the "danger zone" section)
3. User selects destination workspace
4. User gets prompted to confirm the move
5. Insight page gets moved

This needs some design but can be possibly tackled using the design system as well.

### Code of Conduct

By submitting this issue, you agree to follow our [Code of Conduct](https://docs.opensauced.pizza/contributing/code-of-conduct/).

- [ ] I agree to follow this project's Code of Conduct

### Contributing Docs

If you plan on contributing code please read - [Contribution Guide](https://docs.opensauced.pizza/contributing/introduction-to-contributing/)

- [ ]  I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment]
Closing as workspaces are the primary places for insights and you can invite others to your workspace

**Comment by bdougie** [comment]
@brandonroberts we will still need to transfer insights. Xebia has all their work in a personal workspace today.

**Comment by jpmcb** [comment]
FYI - API changes implemented here: https://github.com/open-sauced/api/pull/613: this will require some thought how/if we'll want to handle redirects for insight pages that move.

I think, for now, just 404 is ok until we run into a use case where people want redirects to happen for well known workspace repo insight pages

**Comment by isabensusan** [comment]
Update:
Changes were made to the API to handle this feature from the backend, but only for repository insights [(#613](https://github.com/open-sauced/api/pull/613))
- Opened up a ticket for @jpmcb to replicate the same for contributor insights as well [(#619](https://github.com/open-sauced/api/issues/619))

And now we need to work on the front-end flow for this interaction
