### ISSUE TITLE
[Front-End] Implement `<ContextFilter>` component

### ISSUE THREAD

**Issue by eryc-cc** [open-sauced/app#85]
## Summary

We are implementing 5 opinionated filters that will filter all of the data, and update all of the UI.

As shown in the [**Figma Prototype**](https://www.figma.com/proto/OpVX6WT7dmWqnwRuEvADMF/OpenSauced-%E2%80%94-Insights-(insights.opensauced.pizza)?page-id=463%3A268&node-id=473%3A862&viewport=1174%2C1661%2C2.06&scaling=scale-down-width&starting-point-node-id=473%3A1267), the filter will start with a button, and when you click it, it'll open the options. 

Once you select an option, the filter will retract, and show only the button and that option.

### To-do:
- [x] Implement Atom to storybook: `<ContextFilterOption>`
- [x] Implement Atom to storybook: `<ContextFilterButton>`
- [x] Implement Molecule to storybook: `<ContextFilter>`
- [x] #87
- [x] #88

### Filter Options

We have 5 opinionated pre-defined filters:
- Top 1000 projects (based on stars)
- Projects with more than 5 contributors as of X date (note for API - this is limited to 1k repos)
- Projects with more than 1000 stars
- Most active - project with the most hacktoberfest labeled PRs
- Most spammed - project with the most invalid labeled PRs

## Designs:

Designs can be found in the [Figma File](https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/OpenSauced-%E2%80%94-Insights-(insights.opensauced.pizza)?node-id=463%3A268), [Figma Prototype](https://www.figma.com/proto/OpVX6WT7dmWqnwRuEvADMF/OpenSauced-%E2%80%94-Insights-(insights.opensauced.pizza)?page-id=463%3A268&node-id=473%3A862&viewport=1174%2C1661%2C2.06&scaling=scale-down-width&starting-point-node-id=473%3A1267), or in the issue below:
- [x] #58 

### ContextFilterOption

States:
- Default
- Hover: Text will get darker, and border will become orange
- Focus: Same as hover, plus the orange `ring`

<img width="1307" alt="Screen Shot 2022-07-19 at 8 54 26 PM" src="https://user-images.githubusercontent.com/101464991/179867284-45a48e60-46ab-4f8a-824a-bf488c7750bc.png">

### ContextFilterButton

States:
- Default
- Hover: Background will go 1 step down
- Focus: Same as hover, plus the orange border and `ring`

<img width="1109" alt="Screen Shot 2022-07-19 at 8 54 08 PM" src="https://user-images.githubusercontent.com/101464991/179867270-a902437c-25be-4cf8-92c9-60bae1c723a9.png">

### Context Filter

<img width="1278" alt="Screen Shot 2022-07-19 at 8 43 19 PM" src="https://user-images.githubusercontent.com/101464991/179866272-b297d06e-ae8a-4c1a-90e2-a67c20b5a79f.png">
